const express = require('express')
const { connectionString } = require('./utils/config')
const phonebookRouter = require('./controllers/phonebook')
const additionalRoutes = require('./controllers/additionalRoutes')
const morgan = require('morgan')
const { customMorgan } = require('./utils/loggers')
const { unknownRoute, handleErrors } = require('./utils/middleware')
const cors = require('cors')
const mongoose = require('mongoose')
const app = express()
morgan.token('data', customMorgan)
mongoose.set('strictQuery', true)
mongoose.connect(connectionString).catch((err) => console.error(err))
app.use(express.json())
app.use(cors())
app.use(express.static('build'))
app.use(
  morgan(':method :url :status :res[content-length] - :response-time ms :data')
)
app.use('/api/persons', phonebookRouter)
app.use('/info', additionalRoutes)
app.use(unknownRoute)
app.use(handleErrors)
module.exports = app
